version: "3.9"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      app: node_1
      port: 3000
    depends_on:
      - web
  web:
    image: nginx
    container_name: nginx
    ports:
     - "8080:80"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ./public:/usr/share/nginx/html
